posfibertec/adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main, name='main'),
    re_path(r'^login/$', adminapp.login, name='login'),
    re_path(r'^logout/$', adminapp.logout, name='logout'),
    re_path(r'^password/(?P<user_pk>\d+)/$', adminapp.changepass, name='changepass'),
    re_path(r'^header/$', adminapp.header, name='header'),
    re_path(r'^home/$', adminapp.home, name='home'),
    re_path(r'^slider/add/$', adminapp.slider_add, name='slider_add'),
    re_path(r'^slider/update/(?P<slider_pk>\d+)/$', adminapp.slider_update, name='slider_update'),
    re_path(r'^caption/(?P<caption_pk>\d+)/$', adminapp.caption, name='caption'),
    re_path(r'^content/$', adminapp.content, name='content'),
    re_path(r'^content/update/$', adminapp.content_update, name='content_update'),
    re_path(r'^choose/$', adminapp.choose, name='choose'),
]

posfibertec/posfibertec/urls.py
# from django.contrib import admin
from django.urls import re_path, include
import siteapp.views as siteapp

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^$', siteapp.index, name='index'),
    re_path(r'^about/', siteapp.about, name='about'),
    re_path(r'^services/', siteapp.services, name='services'),
    re_path(r'^portfolio/', siteapp.portfolio, name='portfolio'),
    re_path(r'^contact/', siteapp.contact, name='contact'),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    # re_path('^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posfibertec/adminapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, AdminPasswordChangeForm
from django.contrib.auth.models import User
from adminapp.models import Header, Slider, Caption, Content, Choose


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'username':
                field.widget.attrs['placeholder'] = 'Имя пользователя'
            if field_name == 'password':
                # field.widget = forms.HiddenInput()
                field.widget.attrs['placeholder'] = 'Пароль'


class UserPassChangeForm(AdminPasswordChangeForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'password1':
                field.widget.attrs['placeholder'] = 'Пароль'
            if field_name == 'password2':
                field.widget.attrs['placeholder'] = 'Пароль (еще раз)'
            field.help_text = ''


class HeaderForm(forms.ModelForm):
    class Meta:
        model = Header()
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'logo':
                field.widget.attrs['id'] = 'id-input-file-2'
            if field_name == 'alt':
                field.widget.attrs['placeholder'] = 'алтернативный текст'
            if field_name == 'about' or field_name == 'services' or field_name == 'portfolio' or field_name == 'contact':
                field.widget.attrs['placeholder'] = 'название меню'
            if field_name == 'about_active' or field_name == 'services_active' or field_name == 'portfolio_active' or field_name == 'contact_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'
            field.help_text = ''


class SliderForm(forms.ModelForm):
    class Meta:
        model = Slider
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок слайдера до 50 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Краткое описание к слайдеру до 100 символов'
            if field_name == 'img':
                field.widget.attrs['id'] = 'id-input-file-2'
            if field_name == 'alt':
                field.widget.attrs['placeholder'] = 'алтернативный текст'
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'


class CaptionForm(forms.ModelForm):
    class Meta:
        model = Caption
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок до 100 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Краткое описание до 500 символов'
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'


class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title1' or field_name == 'title2' or field_name == 'title3' or field_name == 'title4':
                field.widget.attrs['placeholder'] = 'Заголовок до 50 символов'
            if field_name == 'text1' or field_name == 'text2' or field_name == 'text3' or field_name == 'text4':
                field.widget.attrs['placeholder'] = 'Длинна текста не более 300 символов'


class ChooseForm(forms.ModelForm):
    class Meta:
        model = Choose
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок до 50 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Длинна текста не более 1000 символов'

posfibertec/adminapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib import auth
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from adminapp.models import Header, Slider, Caption, Content, Choose
from adminapp.forms import UserLoginForm, UserPassChangeForm, HeaderForm, SliderForm, CaptionForm, ContentForm, \
    ChooseForm


@login_required()
def main(request):
    title = 'Админка'
    context = {
        'title': title,
    }

    return render(request, 'adminapp/main.html', context)


def login(request):
    title = 'Вход'
    form = UserLoginForm()
    next_page = request.GET['next'] if 'next' in request.GET.keys() else ''
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('admin:main'))

    context = {
        'title': title,
        'form': form,
        'next': next_page,
    }
    return render(request, 'adminapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def changepass(request, user_pk):
    title = 'Сменить пароль'
    user = get_object_or_404(User, pk=user_pk)

    if user:
        if request.method == 'POST':
            form = UserPassChangeForm(user, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:main'))
        else:
            form = UserPassChangeForm(user)

        context = {
            'title': title,
            'form': form,
        }
        return render(request, 'adminapp/password.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def header(request):
    title = 'Шапка сайта'
    site_header = Header.objects.first() if Header.objects.first() else Header.header_create()
    if site_header:
        if request.method == 'POST':
            form = HeaderForm(request.POST, request.FILES, instance=site_header)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:header'))
        else:
            form = HeaderForm(instance=site_header)

    active = ('active', '', '', '', '', '', '')
    context = {
        'title': title,
        'active': active,
        'form': form,
        'object': site_header,
    }
    return render(request, 'adminapp/header.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def home(request):
    title = 'Главная страница'
    slider = Slider.objects.all() if Slider.objects.all() else Slider.slider_create()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'slider_object': slider,
    }
    return render(request, 'adminapp/home.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def slider_add(request):
    title = 'Добавить слайдер'
    slider = Slider.slider_create()

    if request.method == 'POST':
        form = SliderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:home'))
    else:
        form = SliderForm()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'object': slider,
    }
    return render(request, 'adminapp/slider_add.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def slider_update(request, slider_pk=None):
    title = 'Изменить слайдер'
    slider = get_object_or_404(Slider, pk=slider_pk)

    if slider:
        if request.method == 'POST':
            form = SliderForm(request.POST, request.FILES, instance=slider)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:home'))
        else:
            form = SliderForm(instance=slider)
    else:
        # выполняем в том случае, если БД еще пустая
        slider = Slider.slider_create()
        form = SliderForm(instance=slider)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'object': slider,
    }
    return render(request, 'adminapp/slider.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def caption(request, caption_pk=None):
    title = 'Заголовок'
    if int(caption_pk) != 0:
        caption = get_object_or_404(Caption, pk=caption_pk)
    else:
        caption = Caption.objects.first() if Caption.objects.first() else Caption.caption_create(request)

    print(caption.pk)
    if caption:
        if request.method == 'POST':
            form = CaptionForm(request.POST, instance=caption)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            form = CaptionForm(instance=caption)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'caption_object': caption,
        'form': form,
    }
    return render(request, 'adminapp/caption.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def content(request):
    title = 'Контент'
    content = Content.objects.first() if Content.objects.first() else Content.content_default()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'content_object': content,
    }
    return render(request, 'adminapp/content.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def content_update(request):
    title = 'Изменить контент'
    content = Content.objects.first() if Content.objects.first() else Content.content_create()

    if content:
        if request.method == 'POST':
            form = ContentForm(request.POST, instance=content)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:content'))
        else:
            form = ContentForm(instance=content)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'content_object': content,
    }
    return render(request, 'adminapp/content_update.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def choose(request):
    title = 'Почему мы?'
    choose = Choose.objects.first() if Choose.objects.first() else Choose.choose_create(request)
    if choose:
        if request.method == 'POST':
            form = ChooseForm(request.POST, instance=choose)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:choose'))
        else:
            form = ChooseForm(instance=choose)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
    }
    return render(request, 'adminapp/choose.html', context)

posfibertec/adminapp/templates/adminapp/caption.html
{% extends 'adminapp/a_base.html' %}
{% load staticfiles %}
{% load tags %}

<title>
    {% block title %}
    {{ block.super }} - {{ title }}
    {% endblock %}
</title>

{% block content %}
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        {% include 'adminapp/includes/inc_user_menu.html' %}

    </div><!-- /.navbar-container -->
</div>

<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
				try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    <div id="sidebar" class="sidebar responsive ace-save-state">
        <script type="text/javascript">
					try{ace.settings.loadState('sidebar')}catch(e){}
        </script>

        {% include 'adminapp/includes/inc_menu.html' %}

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>

    <div class="main-content">
        <div class="main-content-inner">
            <div class="page-content">
                <div class="row">
                    <!-- PAGE CONTENT BEGINS -->
                    <div class="col-sm-12">

<!--                        <div class="tabbable tabs-left">-->
<!--                            <ul class="nav nav-tabs" id="myTab3">-->
<!--                                <li class="active">-->
<!--                                    <a data-toggle="tab" href="#slider" aria-expanded="true">-->
<!--                                        <i class="blue ace-icon fa fa-image bigger-110"></i>-->
<!--                                        Слайдер-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                                <li class="">-->
<!--                                    <a data-toggle="tab" href="#caption" aria-expanded="false">-->
<!--                                        <i class="blue ace-icon fa fa-info bigger-110"></i>-->
<!--                                        Заголовок-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                                <li class="">-->
<!--                                    <a data-toggle="tab" href="#container" aria-expanded="false">-->
<!--                                        <i class="blue ace-icon fa fa-bars bigger-110"></i>-->
<!--                                        Содержимое-->
<!--                                    </a>-->
<!--                                </li>-->
<!--                            </ul>-->

<!--                            <div class="tab-content">-->
<!--                                &lt;!&ndash; SLIDER &ndash;&gt;-->
<!--                                <div id="slider" class="tab-pane active">-->
<!--                                    <div class="widget-body">-->
<!--                                        <div class="widget-main">-->
<!--                                            &lt;!&ndash; Добавить слайдер &ndash;&gt;-->
<!--                                            <div class="form-group">-->
<!--                                                <a href="{% url 'admin:slider_add' %}">-->
<!--                                                    <button class="btn btn-white btn-primary" title="Добавить слайдер">-->
<!--                                                        <i class="fa fa-plus"></i>-->
<!--                                                    </button>-->
<!--                                                </a>-->
<!--                                            </div>-->

<!--                                            {% if slider %}-->
<!--                                            {% for slider in slider_object %}-->
<!--                                            <div class="form-group">-->
<!--                                                {% if slider.pk %}-->
<!--                                                <div class="col-xs-12" style="{% if slider.is_active %} opacity:1 {% else %} opacity:0.5 {% endif %}">-->
<!--                                                    <a href="{% url 'admin:slider_update' slider.pk %}"-->
<!--                                                       title="Изменить">-->
<!--                                                        <img src="{{ slider.img|default_slider }}" width="500px"-->
<!--                                                             alt="{{ slider.alt }}">-->
<!--                                                    </a>-->
<!--                                                    <h2>{{ slider.title }}</h2>-->
<!--                                                    <h5>{{ slider.text }}</h5>-->
<!--                                                </div>-->
<!--                                                {% else %}-->
<!--                                                <div class="col-xs-12">-->
<!--                                                    <a href="#">-->
<!--                                                        <img src="{{ slider.img|default_slider }}" width="500px"-->
<!--                                                             alt="">-->
<!--                                                    </a>-->
<!--                                                </div>-->
<!--                                                {% endif %}-->
<!--                                            </div>-->
<!--                                            {% endfor %}-->
<!--                                            {% else %}-->
<!--                                            <div class="col-xs-12">-->
<!--                                                <a href="#">-->
<!--                                                    <img src="{{ slider_object.img|default_slider }}" width="500px"-->
<!--                                                         alt="">-->
<!--                                                </a>-->
<!--                                            </div>-->
<!--                                            {% endif %}-->
<!--                                        </div>-->
<!--                                    </div>-->
<!--                                </div>-->
<!--                                &lt;!&ndash; END SLIDER &ndash;&gt;-->

                                <!-- CAPTION -->
                                <div id="caption" class="tab-pane">
                                    <div class="form-group">
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="col-xs-12">
                                                {{ form.title }}
                                                <p></p>
                                                {{ form.text }}
                                                <p></p>
                                                <div class="col-sx-1">
                                                    <label>
                                                        {{ form.is_active }}
                                                        <span class="lbl"></span>
                                                    </label>
                                                </div>
                                                <!-- кнопки -->
                                                <div class="clearfix">
                                                    <p>&nbsp;</p>
                                                    <button type="submit" class="width-10 btn btn-sm btn-primary">
                                                        <i class="ace-icon fa fa-save"></i>
                                                        <span class="bigger-110">Сохранить</span>
                                                    </button>
<!--                                                    <a href="{% url 'admin:home' %}">-->
<!--                                                        <button class="width-10 btn btn-sm btn-default" type="button">-->
<!--                                                            <i class="ace-icon fa fa-undo"></i>-->
<!--                                                            <span class="bigger-110">Отменить</span>-->
<!--                                                        </button>-->
<!--                                                    </a>-->
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <!-- END CAPTION -->

<!--                                &lt;!&ndash; CONTAINER &ndash;&gt;-->
<!--                                <div id="container" class="tab-pane">-->
<!--                                </div>-->
<!--                                &lt;!&ndash; END CONTAINER &ndash;&gt;-->
<!--                            </div>-->
<!--                        </div>-->
                    </div>
                    <!-- PAGE CONTENT ENDS -->
                </div>
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->

</div><!-- /.main-container -->

{% endblock %}

posfibertec/adminapp/templates/adminapp/home.html
{% extends 'adminapp/a_base.html' %}
{% load staticfiles %}
{% load tags %}

<title>
    {% block title %}
    {{ block.super }} - {{ title }}
    {% endblock %}
</title>

{% block content %}
<div id="navbar" class="navbar navbar-default ace-save-state">
    <div class="navbar-container ace-save-state" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
            <span class="sr-only">Toggle sidebar</span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>

            <span class="icon-bar"></span>
        </button>

        {% include 'adminapp/includes/inc_user_menu.html' %}

    </div><!-- /.navbar-container -->
</div>

<div class="main-container ace-save-state" id="main-container">
    <script type="text/javascript">
				try{ace.settings.loadState('main-container')}catch(e){}
    </script>

    <div id="sidebar" class="sidebar responsive ace-save-state">
        <script type="text/javascript">
					try{ace.settings.loadState('sidebar')}catch(e){}
        </script>

        {% include 'adminapp/includes/inc_menu.html' %}

        <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
            <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state"
               data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
        </div>
    </div>

    <div class="main-content">
        <div class="main-content-inner">
            <div class="page-content">
                <div class="row">
                    <!-- PAGE CONTENT BEGINS -->
                    <div class="col-sm-12">
                        <!-- SLIDER -->
                        <div class="tab-pane active">
                            <div class="widget-body">
                                <div class="widget-main">
                                    <!-- Добавить слайдер -->
                                    <div class="form-group">
                                        <a href="{% url 'admin:slider_add' %}">
                                            <button class="btn btn-white btn-primary" title="Добавить слайдер">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </a>
                                    </div>

                                    {% if slider_object %}
                                    {% for slider in slider_object %}
                                    <div class="form-group">
                                        {% if slider.pk %}
                                        <div class="col-xs-12"
                                             style="{% if slider.is_active %} opacity:1 {% else %} opacity:0.5 {% endif %}">
                                            <a href="{% url 'admin:slider_update' slider.pk %}"
                                               title="Изменить">
                                                <img src="{{ slider.img|default_slider }}" width="500px"
                                                     alt="{{ slider.alt }}">
                                            </a>
                                            <h2>{{ slider.title }}</h2>
                                            <h5>{{ slider.text }}</h5>
                                            <hr style="height:2px; background:#888;">
                                        </div>
                                        {% else %}
                                        <div class="col-xs-12">
                                            <a href="#">
                                                <img src="{{ slider.img|default_slider }}" width="500px"
                                                     alt="">
                                            </a>
                                        </div>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                    {% else %}
                                    <div class="col-xs-12">
                                        <a href="#">
                                            <img src="{{ slider_object.img|default_slider }}" width="500px"
                                                 alt="">
                                        </a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <!-- END SLIDER -->
                    </div>
                    <!-- PAGE CONTENT ENDS -->
                </div>
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->

</div><!-- /.main-container -->

{% endblock %}