posfibertec/adminapp/urls.py
from django.urls import re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    re_path(r'^$', adminapp.main, name='main'),
    re_path(r'^login/$', adminapp.login, name='login'),
    re_path(r'^logout/$', adminapp.logout, name='logout'),
    re_path(r'^password/(?P<user_pk>\d+)/$', adminapp.changepass, name='changepass'),
    re_path(r'^header/$', adminapp.header, name='header'),
    re_path(r'^home/$', adminapp.home, name='home'),
    re_path(r'^slider/add/$', adminapp.slider_add, name='slider_add'),
    re_path(r'^slider/update/(?P<slider_pk>\d+)/$', adminapp.slider_update, name='slider_update'),
    re_path(r'^caption/(?P<caption_pk>\d+)/$', adminapp.caption, name='caption'),
    re_path(r'^content/$', adminapp.content, name='content'),
    re_path(r'^content/update/$', adminapp.content_update, name='content_update'),
    re_path(r'^choose/$', adminapp.choose, name='choose'),
]

posfibertec/posfibertec/urls.py
# from django.contrib import admin
from django.urls import re_path, include
import siteapp.views as siteapp

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^$', siteapp.index, name='index'),
    re_path(r'^about/', siteapp.about, name='about'),
    re_path(r'^services/', siteapp.services, name='services'),
    re_path(r'^portfolio/', siteapp.portfolio, name='portfolio'),
    re_path(r'^contact/', siteapp.contact, name='contact'),
    re_path(r'^admin/', include('adminapp.urls', namespace='admin'))
    # re_path('^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posfibertec/adminapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, AdminPasswordChangeForm
from django.contrib.auth.models import User
from adminapp.models import Header, Slider, Caption, Content, Choose


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'username':
                field.widget.attrs['placeholder'] = 'Имя пользователя'
            if field_name == 'password':
                # field.widget = forms.HiddenInput()
                field.widget.attrs['placeholder'] = 'Пароль'


class UserPassChangeForm(AdminPasswordChangeForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'password1':
                field.widget.attrs['placeholder'] = 'Пароль'
            if field_name == 'password2':
                field.widget.attrs['placeholder'] = 'Пароль (еще раз)'
            field.help_text = ''


class HeaderForm(forms.ModelForm):
    class Meta:
        model = Header()
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'logo':
                field.widget.attrs['id'] = 'id-input-file-2'
            if field_name == 'alt':
                field.widget.attrs['placeholder'] = 'алтернативный текст'
            if field_name == 'about' or field_name == 'services' or field_name == 'portfolio' or field_name == 'contact':
                field.widget.attrs['placeholder'] = 'название меню'
            if field_name == 'about_active' or field_name == 'services_active' or field_name == 'portfolio_active' or field_name == 'contact_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'
            field.help_text = ''


class SliderForm(forms.ModelForm):
    class Meta:
        model = Slider
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок слайдера до 50 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Краткое описание к слайдеру до 100 символов'
            if field_name == 'img':
                field.widget.attrs['id'] = 'id-input-file-2'
            if field_name == 'alt':
                field.widget.attrs['placeholder'] = 'алтернативный текст'
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'


class CaptionForm(forms.ModelForm):
    class Meta:
        model = Caption
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок до 100 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Краткое описание до 500 символов'
            if field_name == 'is_active':
                field.widget.attrs['class'] = 'ace ace-switch ace-switch-4'


class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title1' or field_name == 'title2' or field_name == 'title3' or field_name == 'title4':
                field.widget.attrs['placeholder'] = 'Заголовок до 50 символов'
            if field_name == 'text1' or field_name == 'text2' or field_name == 'text3' or field_name == 'text4':
                field.widget.attrs['placeholder'] = 'Длинна текста не более 300 символов'


class ChooseForm(forms.ModelForm):
    class Meta:
        model = Choose
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'title':
                field.widget.attrs['placeholder'] = 'Заголовок до 50 символов'
            if field_name == 'text':
                field.widget.attrs['placeholder'] = 'Длинна текста не более 1000 символов'

posfibertec/adminapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.contrib import auth
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
from adminapp.models import Header, Slider, Caption, Content, Choose
from adminapp.forms import UserLoginForm, UserPassChangeForm, HeaderForm, SliderForm, CaptionForm, ContentForm, \
    ChooseForm


@login_required()
def main(request):
    title = 'Админка'
    context = {
        'title': title,
    }

    return render(request, 'adminapp/main.html', context)


def login(request):
    title = 'Вход'
    form = UserLoginForm()
    next_page = request.GET['next'] if 'next' in request.GET.keys() else ''
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(request, username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                if 'next' in request.POST.keys():
                    return HttpResponseRedirect(request.POST['next'])
                else:
                    return HttpResponseRedirect(reverse('admin:main'))

    context = {
        'title': title,
        'form': form,
        'next': next_page,
    }
    return render(request, 'adminapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def changepass(request, user_pk):
    title = 'Сменить пароль'
    user = get_object_or_404(User, pk=user_pk)

    if user:
        if request.method == 'POST':
            form = UserPassChangeForm(user, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:main'))
        else:
            form = UserPassChangeForm(user)

        context = {
            'title': title,
            'form': form,
        }
        return render(request, 'adminapp/password.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def header(request):
    title = 'Шапка сайта'
    site_header = Header.objects.first() if Header.objects.first() else Header.header_create()
    if site_header:
        if request.method == 'POST':
            form = HeaderForm(request.POST, request.FILES, instance=site_header)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:header'))
        else:
            form = HeaderForm(instance=site_header)

    active = ('active', '', '', '', '', '', '')
    context = {
        'title': title,
        'active': active,
        'form': form,
        'object': site_header,
    }
    return render(request, 'adminapp/header.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def home(request):
    title = 'Главная страница'
    slider = Slider.objects.all() if Slider.objects.all() else Slider.slider_create()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'slider_object': slider,
    }
    return render(request, 'adminapp/home.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def slider_add(request):
    title = 'Добавить слайдер'
    slider = Slider.slider_create()

    if request.method == 'POST':
        form = SliderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin:home'))
    else:
        form = SliderForm()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'object': slider,
    }
    return render(request, 'adminapp/slider_add.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def slider_update(request, slider_pk=None):
    title = 'Изменить слайдер'
    slider = get_object_or_404(Slider, pk=slider_pk)

    if slider:
        if request.method == 'POST':
            form = SliderForm(request.POST, request.FILES, instance=slider)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:home'))
        else:
            form = SliderForm(instance=slider)
    else:
        # выполняем в том случае, если БД еще пустая
        slider = Slider.slider_create()
        form = SliderForm(instance=slider)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'object': slider,
    }
    return render(request, 'adminapp/slider.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def caption(request, caption_pk=None):
    title = 'Заголовок'
    if int(caption_pk) != 0:
        caption = get_object_or_404(Caption, pk=caption_pk)
    else:
        caption = Caption.objects.first() if Caption.objects.first() else Caption.caption_create(request)

    print(caption.pk)
    if caption:
        if request.method == 'POST':
            form = CaptionForm(request.POST, instance=caption)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            form = CaptionForm(instance=caption)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'caption_object': caption,
        'form': form,
    }
    return render(request, 'adminapp/caption.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def content(request):
    title = 'Контент'
    content = Content.objects.first() if Content.objects.first() else Content.content_default()

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'content_object': content,
    }
    return render(request, 'adminapp/content.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def content_update(request):
    title = 'Изменить контент'
    content = Content.objects.first() if Content.objects.first() else Content.content_create()

    if content:
        if request.method == 'POST':
            form = ContentForm(request.POST, instance=content)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:content'))
        else:
            form = ContentForm(instance=content)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
        'content_object': content,
    }
    return render(request, 'adminapp/content_update.html', context)


@login_required()
@user_passes_test(lambda user: user.is_superuser)
def choose(request):
    title = 'Почему мы?'
    choose = Choose.objects.first() if Choose.objects.first() else Choose.choose_create(request)
    if choose:
        if request.method == 'POST':
            form = ChooseForm(request.POST, instance=choose)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('admin:choose'))
        else:
            form = ChooseForm(instance=choose)

    active = ('', 'active', '', '', '', '', '')
    active_ul = ('active open')
    context = {
        'title': title,
        'active': active,
        'active_ul': active_ul,
        'form': form,
    }
    return render(request, 'adminapp/choose.html', context)

posfibertec/adminapp/templates/adminapp/includes/inc_menu.html
{% load staticfiles %}
<!--{{ request.resolver_match }}-->
<ul class="nav nav-list">
    <li class="{{ active.0 }}">
        <a href="{% url 'admin:header' %}">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Шапка </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="{{ active_ul }}">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-file-o"></i>
            <span class="menu-text"> Главная </span>
        <b class="arrow fa fa-angle-down"></b>
        </a>
        <ul class="submenu">
            <li class="{% if request.resolver_match.url_name == 'home' %} {{ active.1 }} {% endif %}">
                <a href="{% url 'admin:home' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Слайдер
                </a>
                <b class="arrow"></b>
            </li>
            <li class="{% if request.resolver_match.url_name == 'caption' %} {{ active.1 }} {% endif %}">
                {% if caption_object %}
                    {% if caption_object.pk %}
                    <a href="{% url 'admin:caption' caption_object.pk %}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Заголовок
                    </a>
                    {% else %}
                    <a href="{% url 'admin:caption' 0 %}">
                        <i class="menu-icon fa fa-caret-right"></i>
                        Заголовок
                    </a>
                    {% endif %}
                {% else %}
                <a href="{% url 'admin:caption' 0 %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Заголовок
                </a>
                {% endif %}
                <b class="arrow"></b>
            </li>
            <li class="{% if request.resolver_match.url_name == 'content' or request.resolver_match.url_name == 'content_update' %} {{ active.1 }} {% endif %}">
                <a href="{% url 'admin:content' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Содержимое
                </a>
                <b class="arrow"></b>
            </li>
            <li class="{% if request.resolver_match.url_name == 'choose'%} {{ active.1 }} {% endif %}">
                <a href="{% url 'admin:choose' %}">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Содержимое-2
                </a>
                <b class="arrow"></b>
            </li>
            <li class="#">
                <a href="#">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Решения
                </a>
                <b class="arrow"></b>
            </li>
        </ul>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-users"></i>
            <span class="menu-text"> О нас </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-cogs"></i>
            <span class="menu-text"> Услуги </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-picture-o"></i>
            <span class="menu-text"> Порфолио </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-book"></i>
            <span class="menu-text"> Контакты </span>
        </a>
        <b class="arrow"></b>
    </li>
    <li class="">
        <a href="#">
            <i class="menu-icon fa fa-copyright"></i>
            <span class="menu-text"> Подвал </span>
        </a>
        <b class="arrow"></b>
    </li>
</ul><!-- /.nav-list -->

posfibertec/adminapp/templates/adminapp/includes/inc_user_menu.html
<div class="navbar-header pull-left">
    <a href="{% url 'admin:main' %}" class="navbar-brand">
        <small>
            <i class="fa fa-leaf"></i>
            Админка
        </small>
    </a>
</div>

<div class="navbar-buttons navbar-header pull-right" role="navigation">
    <ul class="nav ace-nav">
        <li class="light-blue dropdown-modal">
            <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                <span class="user-info">
									<small>Привет,</small>
									{{ user }}
								</span>
                <i class="ace-icon fa fa-caret-down"></i>
            </a>

            <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                <li>
                    <a href="{% url 'index' %}" target="_blank">
                        <i class="ace-icon fa fa-external-link"></i>
                        Сайт
                    </a>
                </li>

                <li>
                    <a href="{% url 'admin:changepass' user.pk %}">
                        <i class="ace-icon fa fa-key"></i>
                        Сменить пароль
                    </a>
                </li>

                <li class="divider"></li>

                <li>
                    <a href="{% url 'admin:logout' %}">
                        <i class="ace-icon fa fa-power-off"></i>
                        Выйти
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>